version: "3"

services:

  mariadb:
    container_name: mariadb
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    image: mariadb
    restart: on-failure
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_database:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    image: wordpress
    restart: on-failure
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_website_files:/var/www/html

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    image: nginx
    restart: on-failure
    env_file: .env
    networks:
      - inception
    volumes:
      - wordpress_website_files:/var/www/html
    ports:
      - "443:443"


volumes:

  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress_database

  wordpress_website_files:
    name: wordpress_website_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress_website_files


networks:

  inception:
    name: inception
    driver: bridge
