version: "3"

services:

  nginx:
    depends_on:
      - wordpress
    build:
      context: requirements/nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
    image: nginx
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_website_files:/var/www/html
    networks:
      - inception

  wordpress:
    depends_on:
      - mariadb
    build:
      context: requirements/wordpress/
      dockerfile: Dockerfile
    container_name: wordpress
    # ports:
    #   - "9000:9000"
    image: wordpress
    restart: on-failure
    networks:
      - inception
    env_file:
      - .env
    volumes:
      - wordpress_website_files:/var/www/html

  mariadb:
    build:
      context: requirements/mariadb/
      dockerfile: Dockerfile
    container_name: mariadb
    # ports:
    #   - "3306:3306"
    image: mariadb
    restart: on-failure
    networks:
      - inception
    env_file: .env
    volumes:
      - wordpress_database:/var/lib/mysql


volumes:
  wordpress_database:
    name: wordpress_database
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress_database

  wordpress_website_files:
    name: wordpress_website_files
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./wordpress_website_files

networks:
  inception:
    name: inception
    driver: bridge
